version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jokersnguyen998-labs/topdev
    container_name: app
    # restart: unless-stopped
    tty: true
    environment:
      - SERVICE_NAME=app
      - SERVICE_TAGS=dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - topdev

  nginx:
    image: nginx:alpine
    container_name: nginx
    # restart: unless-stopped
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - topdev

  db:
    image: mysql:5.7
    container_name: db
    # restart: unless-stopped
    tty: true
    ports:
      - 13307:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=rootpasswordmysql
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - topdev

networks:
  topdev:
    driver: bridge

volumes:
  mysqldata:
    driver: local
